### ISSUE TITLE
bug on prod

### ISSUE THREAD

**Issue by xmunoz** [tinta/ALLegalsScraper#4]
here is the backtrace:

```
phantom stdout:   http://www.alabamalegals.com/index.cfm?fuseaction=home:102 in onload
...skipping...
    at next (/home/cristina/ALLegalsScraper/node_modules/nightmare/lib/index.js:68:34)
    at f (/home/cristina/ALLegalsScraper/node_modules/nightmare/node_modules/once/once.js:16:25)
    at wrapped (/home/cristina/ALLegalsScraper/node_modules/nightmare/lib/actions.js:403:5)
```

**Comment by whroman** [comment]
Fixed by https://github.com/tinta/ALLegalsScraper/commit/aa20c83fc966eb07cd3023387c239f1af41a46a5
